import os
import re
import argparse

# Functions
def process(x):
    if x not in unique:
        unique.append(x)
    if x not in total:
        total.append(x)
    words.append(x)

def openfile(x, y):
    out = open(x, "w", encoding=y)
    return out

def guess(x):
    if x[-3:] == "ing":
        if x[:-3] in dictionary and x[:-3] not in vocabulary:
            vocabulary.append(word)
    elif x[-3:] == "est":
        if x[:-3] in dictionary and x[:-3] not in vocabulary:
            vocabulary.append(word)
    elif x[-2:] == "ly":
        if x[:-2] in dictionary and x[:-2] not in vocabulary:
            vocabulary.append(word)
    elif x[-2:] == "er":
        if x[:-2] in dictionary and x[:-2] not in vocabulary:
            vocabulary.append(word)
    elif x[:2] == "un":
        if x[2:] in dictionary and x[2:] not in vocabulary:
            vocabulary.append(word)
    elif x[-1:] == "s":
        if x[:-1] in dictionary and x[:-1] not in vocabulary:
            vocabulary.append(word)
    elif x[-1:] == "d":
        if x[:-1] in dictionary and x[:-1] not in vocabulary:
            vocabulary.append(word)
    else:
        if args.dump is not None:
            dump.write(word+"\n")
    return vocabulary

# Variables
text = []
inputs = []
total = []
hyphen = []
vocabulary = []
counter = 0

# Argument parsing
parser = argparse.ArgumentParser(prog='vocabulator',
                                 description='Estimate the vocabularly of a given set of texts.',
                                 epilog='Note: requires a dictionary file generated by makedict.')
parser.add_argument("directory",
                    help='specifies a directory to read texts from')
parser.add_argument("encoding",
                    help='specifies an encoding format to read and save with')
parser.add_argument('-v', '--verbose',
                    help='enables verbose output',
                    dest='verbose',
                    action='store_true')
parser.add_argument('-o', '--output',
                    help='specifices a file to export the vocabulary list to',
                    dest='output')
parser.add_argument('-d', '--dump',
                    help='specifices a file to write failed words to',
                    dest='dump')
args = parser.parse_args()

# Pre-processing
for file in os.listdir(args.directory):
    try:
        text.append(open(args.directory + '/' + file, encoding=args.encoding))
        inputs.append(file)
    except IOError:
        print(file, "is unreadable.")
dictionary = open("dictionary").read().split("\n")
for word in dictionary:
    if "-" in word:
        hyphen.append(word)
if args.dump is not None:
    dump = openfile(args.dump, args.encoding)
        
# Parsing
print("Program may appear frozen while processing!")
for file in text:
    words = []
    unique = []
    for word in file.read().split():
        temp = word.lower()
        temp = re.sub('[\[\]"“?:,{}!.;\'_”()‘’]', '', temp)
        position = temp.find("-")
        if position == -1:
            position = temp.find("—")
        if position > 1:
            if temp not in hyphen:
                temporary = temp[position + 1:]
                temporary = re.sub('[-]', '', temporary)
                process(temporary)
                temp = temp[:position]
                temp = re.sub('[-—]', '', temp)
        process(temp)
    if args.verbose is True:
        print("Total number of words in ", inputs[counter], ":", len(unique))
    counter = counter+1
total.sort()

# Dictionary analysis
for word in total:
    if word in dictionary:
        vocabulary.append(word)
    else:
        vocabulary = guess(word)
if args.dump is not None:
    dump.close()

print("Total vocabulary:", len(vocabulary))

# Export
if args.output is not None:
    out = openfile(args.output, args.encoding)
    for word in vocabulary:
      out.write(word+"\n")
    out.close()
    print("Exported to", args.output)
    quit()  
else:
    quit() 
